#ifndef QCOMMUNICATION_GLOBAL_H
#define QCOMMUNICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QCOMMUNICATION_LIBRARY)
#  define QCOMMUNICATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QCOMMUNICATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QCOMMUNICATION_GLOBAL_H
