#ifndef QNAVIGATIONBAR_GLOBAL_H
#define QNAVIGATIONBAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNAVIGATIONBAR_LIBRARY)
#  define QNAVIGATIONBARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QNAVIGATIONBARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QNAVIGATIONBAR_GLOBAL_H
