#ifndef QMYMSGBOXTHREAD_GLOBAL_H
#define QMYMSGBOXTHREAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMYMSGBOXTHREAD_LIBRARY)
#  define QMYMSGBOXTHREADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMYMSGBOXTHREADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMYMSGBOXTHREAD_GLOBAL_H
